### ISSUE TITLE
bakta_proteins Exception: diamond error! error code: 1

### ISSUE THREAD

**Issue by bananabenana** [oschwengers/bakta#153]
**Describe the bug**
Hi, love the tool. Been using it for a while. I updated to v1.5.1 so I could use the bakta_proteins function on a gene multifasta input. As in, a list of genes I already have and know to be genes. 

Command:
```
bakta_proteins --db db_1.5.1 multifasta_genes.fasta
```
Produces error:
```
--prefix test --output test
        imported: 267
annotate protein sequences...
        detected IPSs: 0
Traceback (most recent call last):
  File "/projects/js66/individuals/benV/Software/conda_envs/conda/envs/bakta_1.5.1/bin/bakta_proteins", line 10, in <module>
    sys.exit(main())
  File "/projects/js66/individuals/benV/Software/conda_envs/conda/envs/bakta_1.5.1/lib/python3.10/site-packages/bakta/proteins.py", line 110, in main
    annotate_aa(aas)
  File "/projects/js66/individuals/benV/Software/conda_envs/conda/envs/bakta_1.5.1/lib/python3.10/site-packages/bakta/proteins.py", line 165, in annotate_aa
    aas_psc, aas_pscc, aas_not_found = psc.search(aas_not_found)
  File "/projects/js66/individuals/benV/Software/conda_envs/conda/envs/bakta_1.5.1/lib/python3.10/site-packages/bakta/psc.py", line 64, in search
    raise Exception(f'diamond error! error code: {proc.returncode}')
Exception: diamond error! error code: 1
```
Log  here: 
[multifasta_genes.log](https://github.com/oschwengers/bakta/files/9650996/multifasta_genes.log)

- Conda install with no issues. All deps are present.
- I can use this input fasta for the regular `bakta` annotation, so the file is legit.

My current workaround is the following:
```
bakta --db db_1.5.1 multifasta_genes.fasta
```
However, this doesn't capture all genes present in the input multifasta.

Any help would be great. 
Thanks

**Comment by oschwengers** [comment]
Hi @bananabenana, thanks for reporting.
Are these amino acid or nucleotide sequences? Due to the lengths in the log, they could be `nt` seqs which is not supported in the  `bakta_proteins` command - it only accepts `aa` seqs.

**Comment by bananabenana** [comment]
Hi @oschwengers,

Thanks for your fast response.

Ahhh this was the problem. Clearly I didn't read the documentation correctly. Thanks!

**Comment by oschwengers** [comment]
No problem - you're welcome!
