### ISSUE TITLE
ERROR: Could not detect/read %s version!', command[0]

### ISSUE THREAD

**Issue by xiongqian123456789** [oschwengers/bakta#253]
Hello!
I used the bakta to annotate the bacteria genomes. It was installed by conda. Here are the log error.

(bakta) [xiongqian@mu02 bac-fa]$ bakta --db /newlustre/home/xiongqian/database/bakta/db-light TB19.bacteria.fa --output ./0
Traceback (most recent call last):
  File "/newlustre/home/xiongqian/miniconda3/envs/bakta/lib/python3.10/site-packages/bakta/utils.py", line 157, in read_tool_output
    sys.exit('ERROR: Could not detect/read %s version!', command[0])
TypeError: exit expected at most 1 argument, got 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/newlustre/home/xiongqian/miniconda3/envs/bakta/bin/bakta", line 10, in <module>
    sys.exit(main())
  File "/newlustre/home/xiongqian/miniconda3/envs/bakta/lib/python3.10/site-packages/bakta/main.py", line 58, in main
    bu.test_dependencies()
  File "/newlustre/home/xiongqian/miniconda3/envs/bakta/lib/python3.10/site-packages/bakta/utils.py", line 253, in test_dependencies
    test_dependency(DEPENDENCY_CIRCOS)
  File "/newlustre/home/xiongqian/miniconda3/envs/bakta/lib/python3.10/site-packages/bakta/utils.py", line 202, in test_dependency
    version = read_tool_output(dependency)
  File "/newlustre/home/xiongqian/miniconda3/envs/bakta/lib/python3.10/site-packages/bakta/utils.py", line 173, in read_tool_output
    sys.exit('ERROR: Could not detect/read %s version!', command[0])
TypeError: exit expected at most 1 argument, got 2

Apprecieate your help!

**Comment by oschwengers** [comment]
Hi. Which Bakta version are you using?
