### ISSUE TITLE
pyrodigal issues with fresh 1.8.2 conda install

### ISSUE THREAD

**Issue by splaisan** [oschwengers/bakta#255]
Hi,

After updating my conda env recently, bakta stopped working and complained about some dependencies version (altair V4 not found, V5 was installed during the update for some other package update).

Based on other error reports I decided to wipe my conda env and create a fresh one from scratch.

The new env now complains not finding Pyrodigal (capital P) while pyrodigal is present (**v 2.3.0 installed**)

```
16:26:35.011 - INFO - UTILS - version=1.8.2
16:26:35.012 - INFO - UTILS - developer: Oliver Schwengers, github.com/oschwengers
16:26:35.012 - INFO - UTILS - command: /opt/miniconda3/envs/bakta/bin/bakta --verbose --db /data/biodata/bakta_db/db --threads 24 --genus Acinetobacter --s --complete --prefix bc01 --output flye_out/bc01_asm/bakta_results flye_out/bc01_asm/bc01_assembly.fasta
16:26:35.012 - INFO - UTILS - local time: 2023-10-30 16:26:35
16:26:35.014 - INFO - UTILS - machine: type=x86_64, cores=88
16:26:35.014 - INFO - UTILS - system: type=Linux, release=5.4.0-165-generic
16:26:35.014 - INFO - UTILS - python: version=3.10.13, implementation=CPython
16:26:35.014 - INFO - CONFIG - threads=24
16:26:35.014 - INFO - CONFIG - verbose=True
16:26:35.014 - INFO - CONFIG - debug=False
16:26:35.014 - INFO - CONFIG - database: type=parameter, path=/data/biodata/bakta_db/db
16:26:35.015 - INFO - CONFIG - tmp-path=/tmp/tmp3s4di35p
16:26:35.015 - INFO - CONFIG - genome-path=/data/NC_projects/4598_AValcek_P2/flye_out/bc01_asm/bc01_assembly.fasta
16:26:35.015 - INFO - CONFIG - min_contig_length=1
16:26:35.015 - INFO - CONFIG - prefix=bc01
16:26:35.015 - INFO - CONFIG - output-path=/data/NC_projects/4598_AValcek_P2/flye_out/bc01_asm/bakta_results
16:26:35.015 - INFO - CONFIG - force=False
16:26:35.015 - INFO - CONFIG - genus=Acinetobacter
16:26:35.015 - INFO - CONFIG - species=baumannii
16:26:35.015 - INFO - CONFIG - strain=0730
16:26:35.015 - INFO - CONFIG - plasmid=None
16:26:35.015 - INFO - CONFIG - complete=True
16:26:35.015 - INFO - CONFIG - prodigal_tf=None
16:26:35.016 - INFO - CONFIG - translation_table=11
16:26:35.016 - INFO - CONFIG - gram=?
16:26:35.016 - INFO - CONFIG - compliant=False
16:26:35.016 - INFO - CONFIG - meta=False
16:26:35.016 - INFO - CONFIG - locus=None
16:26:35.016 - INFO - CONFIG - locus-tag=None
16:26:35.016 - INFO - CONFIG - keep_contig_headers=False
16:26:35.016 - INFO - CONFIG - replicon-table=None
16:26:35.016 - INFO - CONFIG - skip-tRNA=False
16:26:35.016 - INFO - CONFIG - skip-tmRNA=False
16:26:35.016 - INFO - CONFIG - skip-rRNA=False
16:26:35.016 - INFO - CONFIG - skip-ncRNA=False
16:26:35.016 - INFO - CONFIG - skip-ncRNA-region=False
16:26:35.016 - INFO - CONFIG - skip-CRISPR=False
16:26:35.016 - INFO - CONFIG - skip-CDS=False
16:26:35.016 - INFO - CONFIG - skip-pseudo=False
16:26:35.016 - INFO - CONFIG - skip-sORF=False
16:26:35.016 - INFO - CONFIG - skip-gap=False
16:26:35.016 - INFO - CONFIG - skip-ori=False
16:26:35.016 - INFO - CONFIG - skip-plot=False
16:26:35.016 - INFO - DB - detected: major=5, minor=0, type=full, date=2023-02-20
16:26:35.593 - INFO - UTILS - dependency: tool=tRNAscan-SE, version=v2.0.12, path=/opt/miniconda3/envs/bakta/bin/tRNAscan-SE
16:26:35.658 - INFO - UTILS - dependency: tool=Aragorn, version=v1.2.41, path=/opt/miniconda3/envs/bakta/bin/aragorn
16:26:35.686 - INFO - UTILS - dependency: tool=CMscan, version=v1.1.4, path=/opt/miniconda3/envs/bakta/bin/cmscan
16:26:35.711 - INFO - UTILS - dependency: tool=PilerCR, version=v1.6.0, path=/opt/miniconda3/envs/bakta/bin/pilercr
16:26:35.741 - ERROR - UTILS - dependency check failed! tool=Pyrodigal
```

pyrodigal is installed but with small case 'p' 

```
/opt/miniconda3/envs/bakta/bin/pyrodigal
```

I tried adding a Pyrodigal symlink to pyrodigal in the conda env bin folder but it still fails with

```
ERROR: Pyrodigal could not be executed! Please make sure Pyrodigal is installed and executable or skip requiring workflow steps via via '--skip-cds'.
```

thanks for your help

**Comment by splaisan** [comment]
I reinstalled with conda from scratch once more with `conda install -c conda-forge -c bioconda bakta pyrodigal=3.1.0` to hopefully get a better version with Pyrodigal and I do not get a `Pyrodigal` executable, just `pyrodigal`.

```
pyrodigal -V
pyrodigal v3.1.0
```

my command fails with:

`ERROR: Pyrodigal could not be executed! Please make sure Pyrodigal is installed and executable or skip requiring workflow steps via via '--skip-cds'.`

**Comment by splaisan** [comment]
I will first thing monday and post here. I will also rebuild a conda using the new conda version which now finally uses mamba_lib to search for packages (was about time they switched). This only has fixed another issue I had this week.
Good WE!

**Comment by splaisan** [comment]
Hi @oschwengers,

I tried it once more with my existing env to confirm it fails (it did)
I deleted my conda and created a new one with conda 23.
It now works through 'predict & annotate CDSs...' and end with all expected results 

It confirms that the new conda 23.10.0 with mamba resole did build a good environment

problem solved for me
thanks for your support

I reproduce here the last failed run and list of packages as well as the new list of packages in case that can help you figure out who was guilty. I strongly suspect **pyrodigal 2.3** now instead of **3.10** before !


## conda previous bad env

```
bakta --db /data/biodata/bakta_db/db --genus "${genus}"   --species "${species}"   --strain "${strain}"   --prefix "bc${bc}"   --complete   --output out bc01_assembly.fasta

parse genome sequences...
        imported: 3
        filtered & revised: 3
        chromosomes: 1
        plasmids: 2

start annotation...
predict tRNAs...
        found: 74
predict tmRNAs...
        found: 1
predict rRNAs...
        found: 18
predict ncRNAs...
        found: 34
predict ncRNA regions...
        found: 7
predict CRISPR arrays...
        found: 2
predict & annotate CDSs...
Traceback (most recent call last):
  File "/opt/miniconda3/envs/bakta/bin/bakta", line 10, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/bakta/lib/python3.10/site-packages/bakta/main.py", line 228, in main
    cdss = feat_cds.predict(genome, contigs_path)
  File "/opt/miniconda3/envs/bakta/lib/python3.10/site-packages/bakta/features/cds.py", line 41, in predict
    orffinder = pyrodigal.OrfFinder(meta=prodigal_metamode, closed=closed)
AttributeError: module 'pyrodigal' has no attribute 'OrfFinder'
(bakta) $ conda list
# packages in environment at /opt/miniconda3/envs/bakta:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
about-time                4.2.1              pyhd8ed1ab_0    conda-forge
alive-progress            3.0.1              pyhd8ed1ab_0    conda-forge
aragorn                   1.2.41               h031d066_1    bioconda
archspec                  0.2.1              pyhd8ed1ab_1    conda-forge
bakta                     1.8.2              pyhdfd78af_0    bioconda
biopython                 1.81            py310h2372a71_1    conda-forge
blast                     2.14.0               h7d5a4b4_1    bioconda
brotli-python             1.1.0           py310hc6cd4ac_1    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.20.1               hd590300_1    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py310h2fee648_0    conda-forge
charset-normalizer        3.3.1              pyhd8ed1ab_0    conda-forge
circos                    0.69.9               hdfd78af_0    bioconda
curl                      8.4.0                hca28451_0    conda-forge
diamond                   2.1.8                h43eeafb_0    bioconda
entrez-direct             16.2                 he881be0_1    bioconda
expat                     2.5.0                hcb278e6_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
giflib                    5.2.1                h0b41bf4_3    conda-forge
grapheme                  0.6.0              pyhd8ed1ab_0    conda-forge
hmmer                     3.3.2                hdbdd923_4    bioconda
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
infernal                  1.1.4           pl5321h031d066_4    bioconda
isa-l                     2.30.0               hd590300_6    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           19_linux64_openblas    conda-forge
libcblas                  3.9.0           19_linux64_openblas    conda-forge
libcurl                   8.4.0                hca28451_0    conda-forge
libdeflate                1.19                 hd590300_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_2    conda-forge
libgd                     2.3.3                h119a65a_9    conda-forge
libgfortran-ng            13.2.0               h69a702a_2    conda-forge
libgfortran5              13.2.0               ha4646dd_2    conda-forge
libgomp                   13.2.0               h807b86a_2    conda-forge
libidn2                   2.3.4                h166bdaf_0    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           19_linux64_openblas    conda-forge
libnghttp2                1.55.1               h47da74e_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.24          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsqlite                 3.43.2               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_2    conda-forge
libtiff                   4.6.0                ha9c0a0a_2    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp                   1.3.2                h658648e_1    conda-forge
libwebp-base              1.3.2                hd590300_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
ncbi-amrfinderplus        3.11.26              h283d18e_0    bioconda
ncurses                   6.4                  h59595ed_1    conda-forge
numpy                     1.26.0          py310hb13e2d6_0    conda-forge
openssl                   3.1.4                hd590300_0    conda-forge
pbzip2                    1.1.13               h1fcc475_2    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
perl                      5.32.1          4_hd590300_perl5    conda-forge
perl-archive-tar          2.40            pl5321hdfd78af_0    bioconda
perl-b-cow                0.007           pl5321h166bdaf_0    conda-forge
perl-carp                 1.50            pl5321hd8ed1ab_0    conda-forge
perl-clone                0.46            pl5321h166bdaf_0    conda-forge
perl-common-sense         3.75            pl5321hd8ed1ab_0    conda-forge
perl-compress-raw-bzip2   2.201           pl5321h166bdaf_0    conda-forge
perl-compress-raw-zlib    2.202           pl5321h166bdaf_0    conda-forge
perl-config-general       2.65            pl5321hdfd78af_0    bioconda
perl-digest-perl-md5      1.9             pl5321hdfd78af_2    bioconda
perl-encode               3.19            pl5321h166bdaf_0    conda-forge
perl-exporter             5.74            pl5321hd8ed1ab_0    conda-forge
perl-exporter-tiny        1.002002        pl5321hd8ed1ab_0    conda-forge
perl-extutils-config      0.008           pl5321ha770c72_0    conda-forge
perl-extutils-helpers     0.026           pl5321ha770c72_0    conda-forge
perl-extutils-installpaths 0.012           pl5321ha770c72_0    conda-forge
perl-extutils-makemaker   7.70            pl5321hd8ed1ab_0    conda-forge
perl-extutils-pl2bat      0.005           pl5321ha770c72_0    conda-forge
perl-font-ttf             1.06            pl5321hdfd78af_1    bioconda
perl-gd                   2.76            pl5321h5b5514e_1    bioconda
perl-inc-latest           0.500           pl5321ha770c72_0    conda-forge
perl-io-compress          2.201           pl5321hdbdd923_2    bioconda
perl-io-string            1.08            pl5321hdfd78af_4    bioconda
perl-io-zlib              1.14            pl5321hdfd78af_0    bioconda
perl-json                 4.10            pl5321hdfd78af_0    bioconda
perl-json-xs              2.34            pl5321h4ac6f70_6    bioconda
perl-list-moreutils       0.430           pl5321hdfd78af_0    bioconda
perl-list-moreutils-xs    0.430           pl5321h031d066_2    bioconda
perl-math-bezier          0.01            pl5321hdfd78af_2    bioconda
perl-math-round           0.07            pl5321ha770c72_0    conda-forge
perl-math-vecstat         0.08            pl5321hdfd78af_2    bioconda
perl-module-build         0.4232          pl5321ha770c72_0    conda-forge
perl-module-build-tiny    0.039           pl5321h166bdaf_0    conda-forge
perl-module-implementation 0.09            pl5321ha770c72_0    conda-forge
perl-module-runtime       0.016           pl5321ha770c72_0    conda-forge
perl-number-format        1.76            pl5321hdfd78af_0    bioconda
perl-params-validate      1.31            pl5321hec16e2b_0    bioconda
perl-parent               0.241           pl5321hd8ed1ab_0    conda-forge
perl-pathtools            3.75            pl5321h166bdaf_0    conda-forge
perl-readonly             2.05            pl5321ha770c72_0    conda-forge
perl-regexp-common        2017060201      pl5321hd8ed1ab_0    conda-forge
perl-scalar-list-utils    1.63            pl5321h166bdaf_0    conda-forge
perl-set-intspan          1.19            pl5321hdfd78af_2    bioconda
perl-statistics-basic     1.6611          pl5321hdfd78af_3    bioconda
perl-storable             3.15            pl5321h166bdaf_0    conda-forge
perl-svg                  2.87            pl5321hd8ed1ab_0    conda-forge
perl-test-fatal           0.016           pl5321ha770c72_0    conda-forge
perl-text-format          0.62            pl5321hdfd78af_0    bioconda
perl-time-hires           1.9764          pl5321h031d066_4    bioconda
perl-try-tiny             0.31            pl5321ha770c72_0    conda-forge
perl-types-serialiser     1.01            pl5321hdfd78af_0    bioconda
perl-xml-parser           2.44_01         pl5321hc3e0081_1003    conda-forge
pigz                      2.8                  h2797004_0    conda-forge
piler-cr                  1.06                 h4ac6f70_4    bioconda
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
psutil                    5.9.5           py310h2372a71_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyhmmer                   0.10.4          py310h4b81fae_0    bioconda
pyrodigal                 3.1.0           py310h4b81fae_0    bioconda
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.13         hd12c33a_0_cpython    conda-forge
python-isal               1.5.1           py310h2372a71_0    conda-forge
python_abi                3.10                    4_cp310    conda-forge
pyyaml                    6.0.1           py310h2372a71_1    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h2797004_0    conda-forge
trnascan-se               2.0.12          pl5321h031d066_0    bioconda
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   2.0.7              pyhd8ed1ab_0    conda-forge
wget                      1.20.3               ha35d2d1_1    conda-forge
wheel                     0.41.3             pyhd8ed1ab_0    conda-forge
xopen                     1.8.0           py310hff52083_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstandard                 0.21.0          py310h1275a96_1    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

 ## conda 23.0.1 new working env

```
# packages in environment at /opt/miniconda3/envs/bakta:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
about-time                4.2.1              pyhd8ed1ab_0    conda-forge
alive-progress            3.0.1              pyhd8ed1ab_0    conda-forge
aragorn                   1.2.41               h031d066_1    bioconda
archspec                  0.2.2              pyhd8ed1ab_0    conda-forge
bakta                     1.8.2              pyhdfd78af_1    bioconda
biopython                 1.81            py310h2372a71_1    conda-forge
blast                     2.15.0          pl5321h6f7f691_1    bioconda
brotli-python             1.1.0           py310hc6cd4ac_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.21.0               hd590300_0    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py310h2fee648_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
circos                    0.69.9               hdfd78af_0    bioconda
curl                      8.4.0                hca28451_0    conda-forge
diamond                   2.1.8                h43eeafb_0    bioconda
entrez-direct             16.2                 he881be0_1    bioconda
expat                     2.5.0                hcb278e6_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
giflib                    5.2.1                h0b41bf4_3    conda-forge
grapheme                  0.6.0              pyhd8ed1ab_0    conda-forge
hmmer                     3.3.2                hdbdd923_4    bioconda
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
infernal                  1.1.4           pl5321h031d066_4    bioconda
isa-l                     2.30.0               hd590300_6    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           19_linux64_openblas    conda-forge
libcblas                  3.9.0           19_linux64_openblas    conda-forge
libcurl                   8.4.0                hca28451_0    conda-forge
libdeflate                1.17                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgd                     2.3.3                h5aea950_4    conda-forge
libgfortran-ng            13.2.0               h69a702a_3    conda-forge
libgfortran5              13.2.0               ha4646dd_3    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libidn2                   2.3.4                h166bdaf_0    conda-forge
liblapack                 3.9.0           19_linux64_openblas    conda-forge
libnghttp2                1.58.0               h47da74e_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.24          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsqlite                 3.44.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
libtiff                   4.5.0                h6adf6a1_2    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp                   1.2.4                h1daa5a0_1    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxml2                   2.9.14               h22db469_4    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
ncbi-amrfinderplus        3.11.26              h283d18e_0    bioconda
ncbi-vdb                  3.0.8                hdbdd923_0    bioconda
ncurses                   6.4                  h59595ed_2    conda-forge
numpy                     1.26.0          py310hb13e2d6_0    conda-forge
openssl                   3.1.4                hd590300_0    conda-forge
ossuuid                   1.6.2             hf484d3e_1000    conda-forge
pbzip2                    1.1.13               h1fcc475_2    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
perl                      5.32.1          4_hd590300_perl5    conda-forge
perl-alien-build          2.48            pl5321hec16e2b_0    bioconda
perl-alien-libxml2        0.17            pl5321hec16e2b_0    bioconda
perl-archive-tar          2.40            pl5321hdfd78af_0    bioconda
perl-b-cow                0.007           pl5321h166bdaf_0    conda-forge
perl-business-isbn        3.007           pl5321hd8ed1ab_0    conda-forge
perl-business-isbn-data   20210112.006    pl5321hd8ed1ab_0    conda-forge
perl-capture-tiny         0.48            pl5321ha770c72_1    conda-forge
perl-carp                 1.50            pl5321hd8ed1ab_0    conda-forge
perl-clone                0.46            pl5321h166bdaf_0    conda-forge
perl-common-sense         3.75            pl5321hd8ed1ab_0    conda-forge
perl-compress-raw-bzip2   2.201           pl5321h166bdaf_0    conda-forge
perl-compress-raw-zlib    2.202           pl5321h166bdaf_0    conda-forge
perl-config-general       2.65            pl5321hdfd78af_0    bioconda
perl-constant             1.33            pl5321hd8ed1ab_0    conda-forge
perl-digest-perl-md5      1.9             pl5321hdfd78af_2    bioconda
perl-encode               3.19            pl5321h166bdaf_0    conda-forge
perl-exporter             5.74            pl5321hd8ed1ab_0    conda-forge
perl-exporter-tiny        1.002002        pl5321hd8ed1ab_0    conda-forge
perl-extutils-config      0.008           pl5321ha770c72_0    conda-forge
perl-extutils-helpers     0.026           pl5321ha770c72_0    conda-forge
perl-extutils-installpaths 0.012           pl5321ha770c72_0    conda-forge
perl-extutils-makemaker   7.70            pl5321hd8ed1ab_0    conda-forge
perl-extutils-pl2bat      0.005           pl5321ha770c72_0    conda-forge
perl-ffi-checklib         0.28            pl5321hdfd78af_0    bioconda
perl-file-chdir           0.1011          pl5321hd8ed1ab_0    conda-forge
perl-file-path            2.18            pl5321hd8ed1ab_0    conda-forge
perl-file-temp            0.2304          pl5321hd8ed1ab_0    conda-forge
perl-file-which           1.24            pl5321hd8ed1ab_0    conda-forge
perl-font-ttf             1.06            pl5321hdfd78af_1    bioconda
perl-gd                   2.76            pl5321h5b5514e_1    bioconda
perl-importer             0.026           pl5321hd8ed1ab_0    conda-forge
perl-inc-latest           0.500           pl5321ha770c72_0    conda-forge
perl-io-compress          2.201           pl5321hdbdd923_2    bioconda
perl-io-string            1.08            pl5321hdfd78af_4    bioconda
perl-io-zlib              1.14            pl5321hdfd78af_0    bioconda
perl-json                 4.10            pl5321hdfd78af_0    bioconda
perl-json-xs              2.34            pl5321h4ac6f70_6    bioconda
perl-list-moreutils       0.430           pl5321hdfd78af_0    bioconda
perl-list-moreutils-xs    0.430           pl5321h031d066_2    bioconda
perl-math-bezier          0.01            pl5321hdfd78af_2    bioconda
perl-math-round           0.07            pl5321ha770c72_0    conda-forge
perl-math-vecstat         0.08            pl5321hdfd78af_2    bioconda
perl-module-build         0.4234          pl5321ha770c72_0    conda-forge
perl-module-build-tiny    0.039           pl5321h166bdaf_0    conda-forge
perl-module-implementation 0.09            pl5321ha770c72_0    conda-forge
perl-module-runtime       0.016           pl5321hdfd78af_2    bioconda
perl-number-format        1.76            pl5321hdfd78af_0    bioconda
perl-params-validate      1.31            pl5321h031d066_2    bioconda
perl-parent               0.241           pl5321hd8ed1ab_0    conda-forge
perl-path-tiny            0.124           pl5321hd8ed1ab_0    conda-forge
perl-pathtools            3.75            pl5321h166bdaf_0    conda-forge
perl-readonly             2.05            pl5321ha770c72_0    conda-forge
perl-regexp-common        2017060201      pl5321hd8ed1ab_0    conda-forge
perl-scalar-list-utils    1.63            pl5321h166bdaf_0    conda-forge
perl-scope-guard          0.21            pl5321hd8ed1ab_0    conda-forge
perl-set-intspan          1.19            pl5321hdfd78af_2    bioconda
perl-statistics-basic     1.6611          pl5321hdfd78af_3    bioconda
perl-storable             3.15            pl5321h166bdaf_0    conda-forge
perl-sub-info             0.002           pl5321hd8ed1ab_0    conda-forge
perl-svg                  2.87            pl5321hd8ed1ab_0    conda-forge
perl-term-table           0.016           pl5321hdfd78af_0    bioconda
perl-test-fatal           0.016           pl5321ha770c72_0    conda-forge
perl-test-warnings        0.031           pl5321ha770c72_0    conda-forge
perl-test2-suite          0.000145        pl5321hdfd78af_0    bioconda
perl-text-format          0.62            pl5321hdfd78af_0    bioconda
perl-time-hires           1.9764          pl5321h031d066_4    bioconda
perl-try-tiny             0.31            pl5321ha770c72_0    conda-forge
perl-types-serialiser     1.01            pl5321hdfd78af_0    bioconda
perl-uri                  5.17            pl5321ha770c72_0    conda-forge
perl-xml-libxml           2.0207          pl5321h661654b_0    bioconda
perl-xml-namespacesupport 1.12            pl5321hd8ed1ab_0    conda-forge
perl-xml-parser           2.44_01         pl5321hc3e0081_1003    conda-forge
perl-xml-sax              1.02            pl5321hd8ed1ab_0    conda-forge
perl-xml-sax-base         1.09            pl5321hd8ed1ab_0    conda-forge
pigz                      2.8                  h2797004_0    conda-forge
piler-cr                  1.06                 h4ac6f70_4    bioconda
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
psutil                    5.9.5           py310h2372a71_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyhmmer                   0.10.4          py310h4b81fae_0    bioconda
pyrodigal                 2.3.0           py310h4b81fae_1    bioconda
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.13         hd12c33a_0_cpython    conda-forge
python-isal               1.5.2           py310h2372a71_0    conda-forge
python_abi                3.10                    4_cp310    conda-forge
pyyaml                    6.0.1           py310h2372a71_1    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
trnascan-se               2.0.12          pl5321h031d066_0    bioconda
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   2.0.7              pyhd8ed1ab_0    conda-forge
wget                      1.20.3               ha35d2d1_1    conda-forge
wheel                     0.41.3             pyhd8ed1ab_0    conda-forge
xopen                     1.8.0           py310hff52083_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstandard                 0.22.0          py310h1275a96_0    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

**Comment by oschwengers** [comment]
You're welcome. Glad that it's now working. FYI, upcoming Bakta `v1.9.0` will actually use Pyrodigal >= `v3.1.0`.
