### ISSUE TITLE
Option to Skip the AMR detection step

### ISSUE THREAD

**Issue by abelTan131** [oschwengers/bakta#268]
**Is your feature request related to an existing issue or bug?**
Briefly reference any existing issues this is related to.

I run my file and got:
Traceback (most recent call last):
  File "/opt/conda/bin/bakta", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/bakta/main.py", line 275, in main
    expert_amr_found = exp_amr.search(cdss, cds_aa_path)
  File "/opt/conda/lib/python3.8/site-packages/bakta/expert/amrfinder.py", line 47, in search
    raise Exception(f"amrfinder error! error code: {proc.returncode}. Please, try 'amrfinder_update --force_update --database {amrfinderplus_db_path}' to update AMRFinderPlus's internal database.")
Exception: amrfinder error! error code: 1. Please, try 'amrfinder_update --force_update --database /tllhome/abel/bakta/db-light/amrfinderplus-db' to update AMRFinderPlus's internal database.

**Is your new feature related to a general problem?**
Please provide us with a concise description of what the problem is:
- what happened which was *not* expected
- what did *not* happen which was expected
- what would you like to happen or see in the output
I dont want the AMR genes, I just want the gene annotation. Can we skip it?

**Describe the solution you'd like**
Option to skip the AMR detection step, so I dont get this error.

**Describe alternatives you've considered**

**Additional context**
Add any other context or information about your feature request here.

**Comment by oschwengers** [comment]
Hi @abelTan131 , @gracehm ,
thanks for reporting. We also see these issues with the `AMRFinderPlus` update from time to time. However, I'm still puzzled what causes these effects. I have updated the DB download routine and relaxed file permissions which are set during the download/update. Maybe this helps a bit here. This is active in the new [v1.9.2]() patch release. I also published a huge database update this week [v5.1](). You might want to try this one. 

FYI: the `amrfinder_update --force_update --database <path-to-bakta-db>/amrfinderplus-db/` command as suggested by the Bakta error output did the job in my cases.

**Comment by aldertzomer** [comment]
Same problem here. Will try the update. Does it have to do with this amrfinderplus issue: https://github.com/ncbi/amr/issues/89 ?

**Comment by oschwengers** [comment]
Hi @aldertzomer, sorry for the late reply. No, the issue you've referenced is quite old and is already fixed IMHO. So, I don't think that this error is related to that issue. I rather see this caused by the new AMRFinderPlus DB version which is not compatible with former versions. Hence, an update of Bakta with the newest AMRFinderPlus version _and_ an DB update should solve this.

**Comment by DanielleMStevens** [comment]
I was having the same issue. My fix was updating both Bakta (v1.9.3) and AMRFinderPlus with both:

```
amrfinder_update --force_update --database <path-to-bakta-db>/amrfinderplus-db/
amrfinder --force_update
```

Though the first few tries didn't work until I updated the read/write/execute permissions of the amrfinderplus-db directory. Can't say if its the same issue but may be something to check.

**Comment by sariamead** [comment]
I am having the same issue. I've reinstalled Bakta via conda (v1.8.1) and tried the force update for AMRFinderPlus. Bakta seems to work fine until reaching the AMR detection step and then throws the following error: 
Exception: amrfinder error! error code: 1. Please, try 'amrfinder_update --force_update --database db_path to update AMRFinderPlus's internal databases

**Comment by oschwengers** [comment]
Could you please try to update Bakta and AMRFInderPlus to the latest versions and then re-install the Bakta db?

It is certainly related to different Software/Database version dependencies of AMRFinderPlus.

A successful quick test:

```
$ mamba create -p ./conda-env --quiet --yes bakta=1.9.4
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

$ mamba activate ./conda-env/
(/home/oliver/tmp/bakta-test/conda-env) $ bakta_db download --type light
Bakta software version: 1.9.4
Required database schema version: 5
Selected DB type: light
Fetch DB versions...
	... compatible DB versions: 2
Download database: v5.1, type=light, 2024-01-19, DOI: 10.5281/zenodo.10522951, URL: https://zenodo.org/record/10522951/files/db-light.tar.gz...
|████████████████████████████████████████| 1.48G/1.48G [100%] in 40.7s (36.46M/s) 
	... done
Check MD5 sum...
	...database file OK: 31b3fbdceace50930f8607f8d664d3f4
Extract DB tarball: file=<...>/db-light.tar.gz, output=<...>bakta-test
Successfully downloaded Bakta database!
	version: 5.1
	Type: light
	DOI: 10.5281/zenodo.10522951
	path: <...>db-light
Update AMRFinderPlus database...
	... done
Run Bakta using '--db <...>db-light' or set a BAKTA_DB environment variable: 'export BAKTA_DB=<...>/db-light'

$ bakta --db db-light/ --output test ~/software/bakta/bakta/test/data/NC_002127.1.fna
parse genome sequences...
...
start annotation...
...
predict & annotate CDSs...
	predicted: 3 
	discarded spurious: 0
	revised translational exceptions: 0
	detected IPSs: 0
	found PSCCs: 3
	lookup annotations...
	conduct expert systems...
		amrfinder: 0
		protein sequences: 2
	combine annotations and mark hypotheticals...
	revise special cases...
extract sORF...
	potential: 52
	discarded due to overlaps: 36
	discarded spurious: 0
	detected IPSs: 0
	found PSCCs: 0
	lookup annotations...
	filter and combine annotations...
	filtered sORFs: 0
...
Annotation successfully finished in 0:15 [mm:ss].
```

**Comment by StickHu** [comment]
Same problem here. I've using the command line 'amrfinder_update --force_update --database /data/workdir/huwa/annotation/bakta_annotation/db/amrfinderplus-db'

But it failed with that

*** ERROR ***
CURL: Cannot read
  from https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/
  code=6
  error: Could not resolve host: ftp.ncbi.nlm.nih.gov
  version: 8.8.0

HOSTNAME: localhost
SHELL: /bin/bash
PWD: /data/workdir/huwa/annotation/bakta_annotation/db
PATH: /data/workdir/huwa/software/miniconda3/envs/bakta/bin:/data/workdir/huwa/software/miniconda3/condabin:/home/huwa/.local/bin:/home/huwa/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/data/workdir/huwa/software/miniconda3/bin:/data/workdir/huwa/software/miniconda3/bin
Progam name:  amrfinder_update
Command line: amrfinder_update --force_update --database /data/workdir/huwa/annotation/bakta_annotation/db/amrfinderplus-db`

Could you please give me some advice on it? Thanks

**Comment by oschwengers** [comment]
Hi @StickHu ,
this seems to be a generic issue on your site. Looks like your machine cannot access the NCBI FTP server at all. Could you ask a local admin to help out?

**Comment by zexlibioinfo** [comment]
Hi @oschwengers, 

I get a same update error on amrfinderplus database. I have tried to either reinstall bakta, or force update database, or directly download latest database from the amrfinderplus GitHub page but unfortunately can't resolve the issue. It is worthy to mention that I get a new error message running with debug mode: `Protein sequences looks like a nucleotide sequences.`

Here is the command I used:
```
bakta --db <path/to/bakta_db> --output ./bakta_test --prefix test --threads 32 --debug ./nucleotide/NZ_AAKL01000181.1.fna
```

Attach the test sequence:
```
>NZ_AAKL01000181.1
ACCTCCTCNNAAACATTAACTAACATCTCATATTTANTGNAANTTTNNGGNTTTTTTCCC
GATTTATGNTAGCCAAGAATCCTTTATATCCTTTCAGCATTAATATCAATATTCCAAAAT
GGTCCTCTTCATTCTCCAAGCCCCGNANNTCNNNTTCNNCNNNCNNNCCCCCCTTTTTTG
TCTCTTCNNCNTCCCNNTCTTTTTTCTCCCCTTNTACTAGACAGNGTNNNNNCNNNNNNN
CCTCCCTTCTTTCGTCTTTCCTCTTTTCTCCTTCCTNTCCCCCTTTTCTGGGGGGGGAAG
CGCGGCTCCTTTTTTCCCCCCCTCTTCCCCCTNCCCGTTCTCTTCCTGTGCTCCTTCCTC
CCTCCCTTTTCCCCCTGCCCTCGCCTTTCCGGCCTCCTCCCCTCCCCGTGTCCGCTCCCT
TTCCTCCCGCAACCGGCTTTCTCGCTCCCCTCTCCTCCCTCTCCCCTTCCCCCCCTCCTC
TTTGCTTGTCTCTCTCCCTCCTCCTCCCCTCTCTCCCCCCCCTCTTTCCTCTTTCTCCTT
TTTTCTCTCCTCCCTTCTCCCCCTCCCCCCTTTTGTGGTGGGGGGGGGGGGAAACCCCCC
CTTTTTTTTTTTTTTCCCCCCCCCCCCCCCNNNNNNNNNNNNNNNCNNCTTTTTAAAAAA
AAAAAAAAGAGGGGGGGTCTTCTCTTATCCTCCTCCACACACTATACTAAAAACATCAAC
AATATACAATAAATAAATCCATCCAAACAACATCACTACTTATAATAAACTACTAATTCT
AACAACCCCCACAACAACCACACACACACCCTACTAAACTCATAACTACCACACAATACT
CATACACTCTCACCATAAGAACAATAACTCAAATACTACATAAAAAAACAAACATATCCA
TCACTACAACTAATAACACCACACTAAAATATACATAACACCAATCAAAAATACCCACCC
TAATTCTAATACCCCACAAATAACTACTATTTACCAAACCCAACAACCAAAAATACCCAT
ATATTCTAAAAACTTCATACCCAACTAAACTAATCACAAACAAACAATCACACACAACCA
ACACTATCCAACCATCATTTTCCCACCCATATTAACTACTCCATCAAACATAAATACACT
AACACACAATCTCCCATCAACACCACATCCTTCACACAAACAAATCACAAAACTTAACCA
ACTCAAATATCAATTACAACTTCTACCATTATATTCATACACCAAATAACATCTCAACAT
CCATATCTCTCCTATCTAACTATCACATAAAAATAATTCAAATAAAAATATAAACCAAAT
ACTTCCAATTCTCCTCCCTACACCCATCCACTACCTATACCATCAATATCACACTCATAT
TAAAACACAAAACTCCATAACACACCACTCATATAATATTCAAATCTAAAACATTCTTCT
CATAAACAACCAACACAATCCACTAATAATAAACAATCTACTCACAAATTCTACCATCAT
ACCAATACATTACCCTTATACTACCCACTATTTCAAAACCTCTATCCCTAACTACCATAC
TTACTCATATCTCCATACCATCCCTTCACAATTNACATACCAACTATACACACATCTATC
ACATTATTACAATACCACAAATCAACACAATCACACCAATTGTCTCATAACTACACCACC
TTTAACATATTCTACAGATCATTCACATA
```

**Comment by ppflrs** [comment]
Thanks @oschwengers for your work in bakta! Is there any chance to get the option to skip AMR detection added in future releases?

**Comment by marade** [comment]
I'm not having a problem getting AMRFinderPlus to work with Bakta, but I'd like to try -O/--organism with AMRFinderPlus and there's no option for that in Bakta, so I'd either like to be able to skip AMR detection in Bakta and run it myself, or have an option for --organism added. Perhaps --genus and --species from Bakta could be joined with an underscore and fed to --organism in AMRFinderPlus? As always, your hard work on this tool is greatly appreciated.

**Comment by marklyng** [comment]
I am getting the same error, but this time in the [Bakta docker image ](https://hub.docker.com/r/oschwengers/bakta) (v1.11.3) where the entrypoint is `bakta`.

Because the entrypoint to the image is `bakta` there is no way to download new databases or update AMRFinderPlus from within the container.

I'm testing with db-light v6.0 downloaded manually from [Zenodo](https://zenodo.org/records/14916843)

```
docker run --rm -i \
  -v ./raw/seq_run:/data \
  -v "/mnt/c/bio_dbs/bakta_db/db-light":/bakta_db \
  oschwengers/bakta:v1.11.3 \
  --db /bakta_db \
  --prefix barcode07 \
  --output /data/output/assembly/bakta \
  --force \
  --verbose \
  /data/assembly/genomes/barcode07/assembly.fasta

Traceback (most recent call last):
  File "/opt/conda/bin/bakta", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bakta/main.py", line 294, in main
Bakta v1.11.3
Options and arguments:
        input: /data/assembly/genomes/barcode07/assembly.fasta
        db: /bakta_db, version 6.0, light
        translation table: 11
        output: /data/output/assembly/bakta
        force: True
        tmp directory: /tmp/tmpxv2v5hfr
        prefix: barcode07
        threads: 32

Parse genome sequences...
        imported: 58
        filtered & revised: 58
        contigs: 58

Start annotation...
predict tRNAs...
        found: 64
predict tmRNAs...
        found: 1
predict rRNAs...
        found: 10
predict ncRNAs...
        found: 43
predict ncRNA regions...
        found: 56
predict CRISPR arrays...
        found: 0
predict & annotate CDSs...
        predicted: 5740
        discarded spurious: 4
        revised translational exceptions: 0
        skip UPS/IPS detection with light db version
        found PSCCs: 4942
        lookup annotations...
        conduct expert systems...
    expert_amr_found = exp_amr.search(cdss, cds_aa_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bakta/expert/amrfinder.py", line 47, in search
    raise Exception(f"amrfinder error! error code: {proc.returncode}. Please, try 'amrfinder_update --force_update --database {amrfinderplus_db_path}' to update AMRFinderPlus's internal database.")    
Exception: amrfinder error! error code: 1. Please, try 'amrfinder_update --force_update --database /bakta_db/amrfinderplus-db' to update AMRFinderPlus's internal database.
```

```
docker run -i -v ./raw/seq_run:/data -v "/mnt/c/bio_dbs/bakta_db/db-light":/bakta_db oschwengers/bakta:v1.11.3 amrfinder_update --force_update --database /bakta_db/amrfinderplus-db/2024-12-18.1
usage: bakta [--db DB] [--min-contig-length MIN_CONTIG_LENGTH]
             [--prefix PREFIX] [--output OUTPUT] [--force] [--genus GENUS]
             [--species SPECIES] [--strain STRAIN] [--plasmid PLASMID]
             [--complete] [--prodigal-tf PRODIGAL_TF]
             [--translation-table {11,4,25}] [--gram {+,-,?}] [--locus LOCUS]
             [--locus-tag LOCUS_TAG] [--locus-tag-increment {1,5,10}]
             [--keep-contig-headers] [--compliant] [--replicons REPLICONS]
             [--regions REGIONS] [--proteins PROTEINS] [--hmms HMMS] [--meta]
             [--skip-trna] [--skip-tmrna] [--skip-rrna] [--skip-ncrna]
             [--skip-ncrna-region] [--skip-crispr] [--skip-cds]
             [--skip-pseudo] [--skip-sorf] [--skip-gap] [--skip-ori]
             [--skip-filter] [--skip-plot] [--help] [--verbose] [--debug]
             [--threads THREADS] [--tmp-dir TMP_DIR] [--version]
             <genome>
bakta: error: unrecognized arguments: --force_update --database /bakta_db/amrfinderplus-db/2024-12-18.1
```

One suggestion for the docker image could be to not have an entry point at all, similarly to how [StaphB](https://staphb.org/docker-builds/make_containers/) does. This would allow users to do interactive docker containers and also use commands other than `bakta`

**Comment by oschwengers** [comment]
Hey all,
thanks for actively reporting bugs and issues. Since there are a couple of both issues and fixes, I tend to close this and _not_ to add another skipping option. This would be active only for newer Bakta versions which in turn would certainly fix these old bugs. I hope this is OK for most users.

Again, thanks a lot and keep on annotating!

**Comment by conmeehan** [comment]
Hi,

I am still having this issue with the newest version, but using the bakta_proteins (v1.12.0) program. It halts at the same step. Im using bakta database version 6 (reinstalled yesterday) and then separately also updated AMRfp (2026-01-21.1). It also didnt work with the older AMFfp (2024-12-18.1) which auto downloaded with baktadb.

Any help most appreciated!

C
