### ISSUE TITLE
Bakta Web Does Not Work

### ISSUE THREAD

**Issue by Dabiguina94** [oschwengers/bakta#291]
HI! I was currently using Bakta Web and worked great!
But now every time I submit any sequence it says "ERROR" but does not says which one or what I am doing wrong.
There is any way can I solve this?
Also when I use Bakta in my terminal, at the beginning was working OK, but now it does not. I installed Bakta with Conda

Please help!

**Comment by DariaGI** [comment]
Hi, I have the same problem after fixing the issuie with diamond by version downgrading.

**Comment by oschwengers** [comment]
Hi, thanks a lot for reporting!
Indeed, we had an issue in our backend that is already fixed by now. We re-scheduled all jobs of the last 24h. If your jobs have not been re-scheduled, then please just re-submit them.

I hope that everything is working again. If this is not the case, please do not hesitate to reach out and file an issue either  here, or even better in our repository for the web version: https://github.com/ag-computational-bio/bakta-web-ui/issues

**Comment by DariaGI** [comment]
Hi, but I have the same problem with basta installed on my server, not the web version. It doesn't work and report the same error. 
Traceback (most recent call last):
  File "/home/dgutnik/miniconda3/bin/bakta", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/dgutnik/miniconda3/lib/python3.11/site-packages/bakta/main.py", line 228, in main
    cdss = feat_cds.predict(genome, contigs_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dgutnik/miniconda3/lib/python3.11/site-packages/bakta/features/cds.py", line 40, in predict
    orffinder = pyrodigal.OrfFinder(meta=prodigal_metamode, closed=closed)
                ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pyrodigal' has no attribute 'OrfFinder'
~$ pyrodigal --version
pyrodigal v3.4.1

**Comment by oschwengers** [comment]
OK, it seems like you have the wrong Pyrodigal version installed - at least for the installed Bakta version. Since [v1.9.0](https://github.com/oschwengers/bakta/releases/tag/v1.9.0) Bakta supports Pyrodigal versions >=[3.0.0](https://github.com/althonos/pyrodigal/releases/tag/v3.0.0). For Bakta versions <=`1.9.0` you need Pyrodigal <=[2.3.0](https://github.com/althonos/pyrodigal/releases/tag/v2.3.0) as mentioned in https://github.com/oschwengers/bakta/issues/240

So you either downgrade Pyrodigal to <=`v2.3.0`  or upgrade Bakta to >=`v1.9.0`

**Comment by oschwengers** [comment]
Hi, did the solution described above help?

**Comment by Dabiguina94** [comment]
Yes, thank you
