### ISSUE TITLE
Issue with trnascan-SE and bakta v1.9.4

### ISSUE THREAD

**Issue by rubmc97** [oschwengers/bakta#307]
[bin.1.log](https://github.com/user-attachments/files/16335069/bin.1.log)

Hi, I keep getting an issue with tRNA-SE... 
"Traceback (most recent call last):
File "/home/comi/ruben.martinez/miniconda3/envs/bakta-env/bin/bakta", line 10, in
sys.exit(main())
File "/home/comi/ruben.martinez/miniconda3/envs/bakta-env/lib/python3.10/site-packages/bakta/main.py", line 155, in m$ genome['features'][bc.FEATURE_T_RNA] = t_rna.predict_t_rnas(genome, contigs_path)
File "/home/comi/ruben.martinez/miniconda3/envs/bakta-env/lib/python3.10/site-packages/bakta/features/t_rna.py", line$ raise Exception(f'tRNAscan-SE error! error code: {proc.returncode}')
Exception: tRNAscan-SE error! error code: 2". 

I'm using the bakta version 1.9.4. If I run it alone like trnascan-SE -h and with conda list, it seems to be there and working, but keep getting this error when running bakta. 

Thanks!

**Comment by rubmc97** [comment]
I think the problem might have been with the TMPDIR that I was using, as trnascan-SE couldn't modify it.
Sorry for the inconvenience
