### ISSUE TITLE
Numpy.core.getlimits.py UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero. 

### ISSUE THREAD

**Issue by oschwengers** [oschwengers/bakta#347]
Unfortunately, somewhere on the last mile towards [v1.10.0](https://github.com/oschwengers/bakta/releases/tag/v1.10.0), the following `numpy` `UserWarning` started to appeared in each invocation of Bakta:

```
conda-envs/bakta-test/lib/python3.11/site-packages/numpy/_core/getlimits.py:555: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
conda-envs/bakta-test/lib/python3.11/site-packages/numpy/_core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
conda-envs/bakta-test/lib/python3.11/site-packages/numpy/_core/getlimits.py:555: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
conda-envs/bakta-test/lib/python3.11/site-packages/numpy/_core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
```

As reported in #346 and discudded [here](https://moyix.blogspot.com/2022/09/someones-been-messing-with-my-subnormals.html), it seems to be related to some `ffast-math` compilation flag set by any of Bakta's dependency - or dependency's dependency...

If someone has an idea or solution how to solve or circumvent this, please let us know.

**Comment by eri-lim** [comment]
Hi, just for info - would like to report that this has occurred in v1.10.1 as well.

**Comment by pjbiggs** [comment]
Hi - and also in v1.10.3 too.  thanks.

**Comment by oschwengers** [comment]
Thanks for the update. I'm pretty sure, that this error is actually not caused by Bakta itself but some 3rd /4th/5th-party dependency within the Bakta Conda environment. Unfortunately, I have currently no clue what is causing this and also no resources to dive deeper into this. But, since this is not an _error_ but only a _warning_ I tend to let it go and hope that someone will fix this within the causing Conda package.

**Comment by eri-lim** [comment]
Thank you. Just to clarify, it was a fatal error - something like in https://github.com/oschwengers/bakta/issues/346, and then Bakta crashes with that message. So, just notifying in case anyone else experiences this.

**Comment by oschwengers** [comment]
OK, thanks for letting us know, but these are two unrelated things: one warning (the subject of this issue) and then, an addition fatal error. To keep these things apart from each other, could you please open a dedicated issue for the fatal error describing it in more detail (input/output/logs/etc)?

**Comment by eri-lim** [comment]
I went to obtain the details but it seems I am now unable to reproduce the crash (it runs again, but also I have redownloaded the database in the process, using the light database). Thanks for the instructions regarding the error. If I encounter it reproducibly, I will open a dedicated issue. 

Thank you for your hard work on Bakta!

**Comment by snail123815** [comment]
Hi,

I added this to `__init__.py` to make warnings fail:

```python
import warnings
warnings.simplefilter("error", UserWarning)
```

And got the following Traceback. I will suggest checking settings related with color. Or, maybe different versions of matplotlib + numpy combination?

```
Traceback (most recent call last):
  File "/vol/local/conda_envs/bakta/bin/bakta", line 6, in <module>
    from bakta.main import main
  File "/vol/local/conda_envs/bakta/lib/python3.11/site-packages/bakta/main.py", line 37, in <module>
    import bakta.plot as plot
  File "/vol/local/conda_envs/bakta/lib/python3.11/site-packages/bakta/plot.py", line 15, in <module>
    from matplotlib.patches import Patch
  File "/vol/local/conda_envs/bakta/lib/python3.11/site-packages/matplotlib/__init__.py", line 997, in <module>
    rcParamsDefault = _rc_params_in_file(
                      ^^^^^^^^^^^^^^^^^^^
  File "/vol/local/conda_envs/bakta/lib/python3.11/site-packages/matplotlib/__init__.py", line 934, in _rc_params_in_file
    config[key] = val  # try to convert to proper type or raise
    ~~~~~~^^^^^
  File "/vol/local/conda_envs/bakta/lib/python3.11/site-packages/matplotlib/__init__.py", line 769, in __setitem__
    cval = self.validate[key](val)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/vol/local/conda_envs/bakta/lib/python3.11/site-packages/matplotlib/rcsetup.py", line 342, in validate_color
    if is_color_like(s):
       ^^^^^^^^^^^^^^^^
  File "/vol/local/conda_envs/bakta/lib/python3.11/site-packages/matplotlib/colors.py", line 229, in is_color_like
    to_rgba(c)
  File "/vol/local/conda_envs/bakta/lib/python3.11/site-packages/matplotlib/colors.py", line 316, in to_rgba
    rgba = _to_rgba_no_colorcycle(c, alpha)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vol/local/conda_envs/bakta/lib/python3.11/site-packages/matplotlib/colors.py", line 338, in _to_rgba_no_colorcycle
    if c is np.ma.masked:
            ^^^^^
  File "/vol/local/conda_envs/bakta/lib/python3.11/site-packages/numpy/__init__.py", line 346, in __getattr__
    import numpy.ma as ma
  File "/vol/local/conda_envs/bakta/lib/python3.11/site-packages/numpy/ma/__init__.py", line 42, in <module>
    from . import core
  File "/vol/local/conda_envs/bakta/lib/python3.11/site-packages/numpy/ma/core.py", line 201, in <module>
    info = np.finfo(sctype)
           ^^^^^^^^^^^^^^^^
  File "/vol/local/conda_envs/bakta/lib/python3.11/site-packages/numpy/_core/getlimits.py", line 544, in __new__
    obj = object.__new__(cls)._init(dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vol/local/conda_envs/bakta/lib/python3.11/site-packages/numpy/_core/getlimits.py", line 558, in _init
    setattr(self, word, getattr(machar, word).flat[0])
                        ^^^^^^^^^^^^^^^^^^^^^
  File "/vol/local/conda_envs/bakta/lib/python3.11/site-packages/numpy/_core/getlimits.py", line 81, in smallest_subnormal
    warnings.warn(
UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
```

**Comment by oschwengers** [comment]
Thank you very much @snail123815 ! This really helps to trace and identify the source of this behavior. However, I'm still puzzled how to deactivate this...

**Comment by snail123815** [comment]
So am I @oschwengers. After some search it seems that the problem is more upstream and not consistent in different environments. Seems to be related with the building of some packages with `-ffast-math` switch.

I found this post **https://github.com/Qiskit/qiskit-aer/pull/1469** which might be useful.

---
For me, downgrade `numpy` to version 1 (1.26) and the warning is gone.

Or ignore this warning explicitly by adding in the `__init__.py`

```python
import warnings
warnings.filterwarnings("ignore", message="The value of the smallest subnormal for")
```

**Comment by oschwengers** [comment]
Thanks @snail123815 for the hint. This will be part of the next patch release!

**Comment by oschwengers** [comment]
This should be properly ignored by https://github.com/oschwengers/bakta/releases/tag/v1.11.1

So, I close this for now. Any comments/hints/feedback on how to fix the cause for this, please to not hesitate to comment/re-open this. Thanks everyone!
