### ISSUE TITLE
sqlite3.OperationalError: invalid uri authority: db

### ISSUE THREAD

**Issue by replikation** [oschwengers/bakta#80]
Hi,

i would really like to use your program, however i get an SQL error when running

* commands used with bakta:1.2.1 (installed via conda)
* don't know SQL so I don't understand the error (e.g. permission issue or something similar?)

## steps to create the error
```bash
# get db
wget --no-check-certificate https://zenodo.org/record/5215743/files/db.tar.gz
tar xzf db.tar.gz 
export BAKTA_DB=./db
amrfinder_update --force_update --database db/amrfinderplus-db/

# get a genome
wget "https://www.ncbi.nlm.nih.gov/sviewer/viewer.cgi?tool=portal&save=file&log$=seqview&db=nuccore&report=fasta&id=1543356152" 
mv viewer.cgi\?tool\=portal\&save\=file\&log\$\=seqview\&db\=nuccore\&report\=fasta\&id\=1543356152 genome.fasta

# run bakta producing an error
bakta --output results --threads 16  genome.fasta 
```

## error log
```python
parse genome sequences...
	imported: 1
	filtered & revised: 1
	contigs: 1
predict tRNAs...
	found: 88
predict tmRNAs...
	found: 1
predict rRNAs...
	found: 22
predict ncRNAs...
	found: 160
predict ncRNA regions...
	found: 52
predict CRISPR arrays...
	found: 2
predict & annotate CDSs...
	predicted: 4583 
	discarded spurious: 5
--- Logging error ---
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/bakta/ups.py", line 29, in lookup
    with sqlite3.connect(f"file:{cfg.db_path.joinpath('bakta.db')}?mode=ro", uri=True, check_same_thread=False) as conn:
sqlite3.OperationalError: invalid uri authority: db

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/opt/conda/bin/bakta", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/bakta/main.py", line 254, in main
    cdss_ups, cdss_not_found = ups.lookup(cdss)
  File "/opt/conda/lib/python3.7/site-packages/bakta/ups.py", line 56, in lookup
    log.exception('Could not read UPSs from db!', ex)
Message: 'Could not read UPSs from db!'
Arguments: (OperationalError('invalid uri authority: db'),)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/bakta/ups.py", line 29, in lookup
    with sqlite3.connect(f"file:{cfg.db_path.joinpath('bakta.db')}?mode=ro", uri=True, check_same_thread=False) as conn:
sqlite3.OperationalError: invalid uri authority: db

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/bakta", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/bakta/main.py", line 254, in main
    cdss_ups, cdss_not_found = ups.lookup(cdss)
  File "/opt/conda/lib/python3.7/site-packages/bakta/ups.py", line 57, in lookup
    raise Exception("SQL error!", ex)
Exception: ('SQL error!', OperationalError('invalid uri authority: db'))
```

**Comment by oschwengers** [comment]
Hi, thanks for reporting this.
I tried to reproduce the error step by step as pointed out above based on a fresh conda environment: `mamba create -p conda-env python=3.7 bakta=1.2.1`, the listed genome and a fresh download of the database.
However, bakta succeeded w/o any issues. 

Could you provide some more information regarding your system, etc:
```bash
$ conda list | grep python
biopython                 1.79             py37h5e8e339_0    conda-forge
python                    3.7.10          hb7a2778_102_cpython    conda-forge
python-isal               0.11.1           py37h5e8e339_0    conda-forge
python_abi                3.7                     2_cp37m    conda-forge

$ conda list | grep sql
sqlite                    3.36.0               h9cd32fc_2    conda-forge
```

as well as the log file of a `--verbose` execution?

**Comment by replikation** [comment]
* figured out the error, apparently I cannot run bakta it in `/` for some reason, but it works in a home dir. seems like a pathing issue of sql
